# Generated by Django 4.2.6 on 2024-05-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(unique=True)),
                ('hash', models.CharField(max_length=150, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.pincode')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question_text', models.CharField(max_length=255)),
                ('point_value', models.IntegerField()),
                ('answer_a', models.CharField(max_length=255)),
                ('answer_b', models.CharField(max_length=255)),
                ('answer_c', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('answered_correctly', models.BooleanField(default=None, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.test')),
            ],
        ),
    ]
