# Generated by Django 4.2.6 on 2024-05-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
