# Generated by Django 5.0.1 on 2025-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='num_of_questions_max',
            field=models.IntegerField(default=None),
        ),
    ]
