# Generated by Django 5.0.1 on 2025-02-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_test_num_of_questions_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
