# Generated by Django 4.2.6 on 2024-05-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_test_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
