# Generated by Django 5.0.1 on 2024-05-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_test_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered_correctly',
        ),
        migrations.AddField(
            model_name='question',
            name='picked_answer',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
