# Generated by Django 5.0.1 on 2024-05-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_remove_question_answered_correctly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='points',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
