# Generated by Django 5.0.1 on 2025-02-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_fontsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
