# Generated by Django 5.0.1 on 2024-07-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_test_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectorPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(unique=True)),
            ],
        ),
    ]
