# Generated by Django 5.0.1 on 2024-07-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_emailinpv31_lectorpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='lector_pin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.lectorpin'),
        ),
    ]
