# Generated by Django 5.0.1 on 2024-07-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_emailinpv31_pincode_lector_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='name_surname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
