# Generated by Django 5.0.1 on 2024-07-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_emailinpv31_course_remove_pincode_lector_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='course_pin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.course'),
        ),
    ]
